// This is an autogenerated config file, any changes to this file will be overwritten

#ifndef TZ_SECURE_MEMORY_AUTOGEN_H
#define TZ_SECURE_MEMORY_AUTOGEN_H

#define TZ_S_FLASH_START  (134496256)
#define TZ_S_RAM_START    (536870912)
#define TZ_S_FLASH_SIZE   (122880)
#define TZ_S_RAM_SIZE     (32768)
#define TZ_S_FLASH_END    (TZ_S_FLASH_START + TZ_S_FLASH_SIZE)
#define TZ_S_RAM_END      (TZ_S_RAM_START + TZ_S_RAM_SIZE)

#endif // TZ_SECURE_MEMORY_AUTOGEN_H
