// This is an autogenerated config file, any changes to this file will be overwritten

#ifndef TZ_SERVICE_CONFIG_AUTOGEN_H
#define TZ_SERVICE_CONFIG_AUTOGEN_H

#define TZ_SERVICE_ATTESTATION_PRESENT
#define TZ_SERVICE_MSC_PRESENT
#define TZ_SERVICE_NVM3_PRESENT
#define TZ_SERVICE_PSA_CRYPTO_PRESENT
#define TZ_SERVICE_SYSCFG_PRESENT


#endif // TZ_SERVICE_CONFIG_AUTOGEN_H
