// This is an autogenerated file, any changes to this file will be overwritten.

#ifndef SLI_TZ_S_INTERFACE_FUNCS_AUTOGEN_H
#define SLI_TZ_S_INTERFACE_FUNCS_AUTOGEN_H

//------------------------------------------------------------------------------
// Local typedefs

// Function pointer conforming to the PSA Crypto secure function signature.
typedef int32_t (*iovec_fn) (psa_invec *in_vec,
                             size_t in_len,
                             psa_outvec *out_vec,
                             size_t out_len);

// Function pointer conforming to syscfg simple function signature.
typedef uint32_t (*sli_tz_simple_fn) (uint32_t arg);

// Function pointer conforming to syscfg simple function signature with no args.
typedef uint32_t (*sli_tz_simple_fn_no_args) (void);

//------------------------------------------------------------------------------
// Secure service function tables

#if defined(TZ_SERVICE_PSA_CRYPTO_PRESENT)
static const iovec_fn crypto_function_table[] = {
(iovec_fn)tfm_crypto_get_key_attributes,
(iovec_fn)tfm_crypto_reset_key_attributes,
(iovec_fn)tfm_crypto_open_key,
(iovec_fn)tfm_crypto_close_key,
(iovec_fn)tfm_crypto_import_key,
(iovec_fn)tfm_crypto_destroy_key,
(iovec_fn)tfm_crypto_export_key,
(iovec_fn)tfm_crypto_export_public_key,
(iovec_fn)tfm_crypto_purge_key,
(iovec_fn)tfm_crypto_copy_key,
(iovec_fn)tfm_crypto_generate_random,
(iovec_fn)tfm_crypto_generate_key,
(iovec_fn)tfm_crypto_generate_key_custom,
(iovec_fn)tfm_crypto_generate_key_ext,

};
#endif // TZ_SERVICE_PSA_CRYPTO_PRESENT

#if defined(TZ_SERVICE_PSA_ITS_PRESENT) || defined(TZ_SERVICE_NVM3_PRESENT)
static const iovec_fn nvm3_function_table[] = {


};
#endif // TZ_SERVICE_PSA_ITS_PRESENT || TZ_SERVICE_NVM3_PRESENT

#if defined(TZ_SERVICE_PSA_ITS_PRESENT)
static const iovec_fn its_function_table[] = {

};
#endif // TZ_SERVICE_PSA_ITS_PRESENT

#if defined(TZ_SERVICE_SE_MANAGER_PRESENT)
static const iovec_fn se_manager_function_table[] = {

};
#endif // TZ_SERVICE_SE_MANAGER_PRESENT

#if defined(TZ_SERVICE_ATTESTATION_PRESENT)
static const iovec_fn attestation_function_table[] = {
  (iovec_fn)sli_tz_attestation_get_public_key,
(iovec_fn)sli_initial_attest_get_token,
(iovec_fn)sli_initial_attest_get_token_size,

};
#endif // TZ_SERVICE_ATTESTATION_PRESENT

#if defined(TZ_SERVICE_SYSCFG_PRESENT) || defined(TZ_SERVICE_MSC_PRESENT)
static const sli_tz_simple_fn simple_function_table[] = {
  (sli_tz_simple_fn)sli_tz_msc_set_readctrl,
(sli_tz_simple_fn)sli_tz_msc_set_pagelock,
(sli_tz_simple_fn)sli_tz_msc_get_pagelock,
(sli_tz_simple_fn)sli_tz_msc_set_misclockword,
(sli_tz_simple_fn)sli_tz_syscfg_mask_dmem0retnctrl_register,

};

static const sli_tz_simple_fn_no_args simple_function_table_no_args[] = {
  (sli_tz_simple_fn_no_args)sli_tz_msc_get_locked,
(sli_tz_simple_fn_no_args)sli_tz_msc_set_locked,
(sli_tz_simple_fn_no_args)sli_tz_msc_set_unlocked,
(sli_tz_simple_fn_no_args)sli_tz_msc_get_readctrl,
(sli_tz_simple_fn_no_args)sli_tz_msc_get_userdata_size,
(sli_tz_simple_fn_no_args)sli_tz_msc_get_misclockword,
(sli_tz_simple_fn_no_args)sli_tz_syscfg_read_chiprev_register,
(sli_tz_simple_fn_no_args)sli_tz_syscfg_read_dmem0retnctrl_register,
(sli_tz_simple_fn_no_args)sli_tz_syscfg_zero_dmem0retnctrl_register,
(sli_tz_simple_fn_no_args)sli_tz_syscfg_set_systicextclken_cfgsystic,
(sli_tz_simple_fn_no_args)sli_tz_syscfg_clear_systicextclken_cfgsystic,

};
#endif // TZ_SERVICE_SYSCFG_PRESENT || TZ_SERVICE_MSC_PRESENT

#endif // SLI_TZ_S_INTERFACE_FUNCS_AUTOGEN_H
