// This is an autogenerated config file, any changes to this file will be overwritten

#ifndef TZ_SECURE_MEMORY_AUTOGEN_H
#define TZ_SECURE_MEMORY_AUTOGEN_H

#define TZ_S_FLASH_START  (134217728)
#define TZ_S_RAM_START    (536870912)
#define TZ_S_FLASH_SIZE   (180224)
#define TZ_S_RAM_SIZE     (12288)
#define TZ_S_FLASH_END    (TZ_S_FLASH_START + TZ_S_FLASH_SIZE)
#define TZ_S_RAM_END      (TZ_S_RAM_START + TZ_S_RAM_SIZE)

#endif // TZ_SECURE_MEMORY_AUTOGEN_H
